[can_ids]
 vehicle_speed = 0x0D1
 traction_control = 0x0D3
 traction_control_mode = 0x0D3
 wheel_speeds = 0x0D4
 throttle_pedal_position = 0x140
 throttle_plate_position = 0x140
 clutch_switch = 0x140
 rpm = 0x141
 gear = 0x141
 headlights = 0x152
 handbrake_switch = 0x152
 reverse_switch = 0x152
 brake_switch = 0x152
 fuel_level = 0x282
 turn_signals = 0x282
 seatbelt_driver = 0x282
 coolant_temp = 0x360
 oil_temp = 0x360
 cruise_control_speed = 0x360
 cruise_control_status = 0x360
 cruise_control_set = 0x360
 boost_pressure = 0x360
 fuel_consumption = 0x360
 oil_pressure_warning = 0x361
 check_engine_light = 0x361
 fog_lights = 0x374
 tpms_warning = 0x374
 door_states = 0x375
 dimmer_dial = 0x376
 odometer = 0x6D1

[conversation_ids]
 send_id = 0x7E0
 send_id_2 = 0x7DF
 ecu_response_id = 0x7E8

[current_data_mode]
 [current_data_mode.engine_load]
  sent_bytes = 2
  pid = 0x04
  response_length = 1
 [current_data_mode.fuel_pressure]
  sent_bytes = 2
  pid = 0x0A
  response_length = 1
 [current_data_mode.intake_manifold_absolute_pressure]
  sent_bytes = 2
  pid = 0x0B
  response_length = 1
 [current_data_mode.timing_advance]
  sent_bytes = 2
  pid = 0x0E
  response_length = 1
 [current_data_mode.intake_air_temperature]
  sent_bytes = 2
  pid = 0x0F
  response_length = 1
 [current_data_mode.mass_air_flow]
  sent_bytes = 2
  pid = 0x10
  response_length = 2
 [current_data_mode.throttle_position]
  sent_bytes = 2
  pid = 0x11
  response_length = 1
#  [current_data_mode.fuel_level]
#   sent_bytes = 2
#   pid = 0x2F
#   response_length = 1
[mode_ids]
 current_data = 0x02
